### ISSUE TITLE
Suggestion: header_inc.php

### ISSUE THREAD

**Issue by TheCrazyT** [robbiet480/MineAdmin#10]
https://github.com/robbiet480/MineAdmin/blob/master/header_inc.php

There should be a closing php-tag ?>
Also ... why don't you implement the top-menu inside?
Currently you are using code for the menu in every single file ... thats not very useful if you might need to change every file when you want to modify the menu for example.

**Comment by robbiet480** [comment]
The closing PHP tag was removed in the previous owner (Firestar's) version because it is not required in PHP.

The menu code has been moved in my branch and will be reflected/updated as soon as I push my code up (soon)
