### ISSUE TITLE
actions.php - Linux based stop/start/restart functions

### ISSUE THREAD

**Issue by camondraconis** [robbiet480/MineAdmin#19]
Hello,

I have been reviewing why the "Start/Stop/Restart" actions in the mineadmin gui do not work in linux. I have found an error

The screen commands point to Minecraft_Mod.jar being located @ "/opt/Minecraft_Mod.jar" as opposed to calling the variable from config.php.

**Comment by emirin** [comment]
Currently we run this for linux users:
                shell_exec('screen -dmS ' . $MCSERVER['SERVICENAME'] . ' java -Xmx'.$GENERAL["memory"].' -Xms'.$GENERAL["memory"].' -jar /opt/Minecraft_Mod.jar');

How does this differ from your current way of rebooting your server?

**Comment by emirin** [comment]
oops didn't mean to close >_<

**Comment by camondraconis** [comment]
Thats cool, I didnt mean to not have a body in the Issue OP.

**Comment by emirin** [comment]
Btw we changed it so instead of /opt/ you get your server loc varable.
