### ISSUE TITLE
Session fixation, session hijacking vulnerabilities found

### ISSUE THREAD

**Issue by katanacrimson** [robbiet480/MineAdmin#5]
As the IP and useragent for the session owner are not validated when loading session data around session_start(), a session fixation vulnerability and session hijacking vulnerability currently exists in this application.

Simply by grabbing a victim's session ID (which can be easily done by stealing the session cookie, or if cookies are disabled, via the request url) an attacker can steal the user's login session and gain access to the system as if they were the victim.

Additionally, there exists an opening for a session fixation attack, where the attacker specifies the session id in linking to the page, which the user clicks on, logs in, and goes about their business.  Afterwards, the attacker uses the same URL that they provided the user to gain access under the victim's login.

**Comment by robbiet480** [comment]
can you push some code for this?

**Comment by katanacrimson** [comment]
Unfortunately, I'm still working with the rest of the OpenFlame dev team on a set of classes that would provide secure session handling -- the classes are still in testing, and are even undergoing a rewrite.

If you want to try messing with them, they're available here:
https://github.com/OpenFlame/OpenFlame-Framework/blob/master/src/OfSession.php
https://github.com/OpenFlame/OpenFlame-Framework/blob/master/src/OfUser.php

The branch containing the highly experimental (and untested) rewrite is available here, as well:
https://github.com/OpenFlame/OpenFlame-Framework/blob/ofsession-properties/src/OfSession.php
https://github.com/OpenFlame/OpenFlame-Framework/blob/ofsession-properties/src/OfUser.php

**Comment by Daenks** [comment]
SUPPLEMENTARY BUG REPORT: If you're logged in as a user, and your user is deleted--your session is not invalidated. You can continue to administer the server until you log out.

**Comment by chemicalfire** [comment]
so we need to add unique session tokens?
