### ISSUE TITLE
HTML charset not defined, possible cross site scripting vulnerability

### ISSUE THREAD

**Issue by katanacrimson** [robbiet480/MineAdmin#6]
All HTML pages should define the charset in use for the page, as otherwise there leaves a potential opening for cross-site-scripting against internet explorer users by way of UTF-7 -- as explained by a XSS expert in this blog post: http://blog.kotowicz.net/2010/10/xss-hackme-challenge-solution-part-2.html

**Comment by dennistang** [comment]
This has been fixed in commit https://github.com/robbiet480/MineAdmin/commit/f01129353c6642081e85596fdc8c73ddafb0ee2d/.

That should cover all the pages but let me know if I missed something!
