### ISSUE TITLE
Stronger password hashing

### ISSUE THREAD

**Issue by katanacrimson** [robbiet480/MineAdmin#7]
I'd like to suggest the use of a password hashing framework, phpass.
It's used in several open source applications such as phpBB and Drupal 7 beta

Currently the official version only uses md5, however myself and several other developers have modified the library ourselves and released a version which uses sha512, making the resulting password hashes _extremely_ tough to crack.

The latest version of our modifications can be obtained here: https://github.com/OpenFlame/OpenFlame-Framework/blob/master/src/OfHash.php
It's also licensed under the MIT License, which is extremely permissive -- any use of the code is permitted, so long as credit to the original developers is retained.  Full license text (two paragraphs) is available here: http://opensource.org/licenses/mit-license.php

If you'd like some implementation examples, I'd be happy to provide them.

**Comment by robbiet480** [comment]
I'd be more then happy to use this password hasher instead of the existing one. However, the passwords as of version 1.0.0 (my version, coming soon) are stored in the users table of the database. These passwords are MySQL safe I am guessing? Implementation examples/you patching the code for it would be much appreciated.

**Comment by katanacrimson** [comment]
The password hashes would look similar the following: 
    $O$Bm3S4byeCnk3hLAL2ga3k4CtZM5frA0
All OfHash produced hashes are prefixed with $O$ as well.
You'd need an appropriate length column in your SQL table to handle it though -- the example is of the standard hash length, so try to fit the column to it.

As for implementation, example:
    // include OfHash file beforehand however you want
    $hash = new OfHash();
    // get our stored password hash here
    // $stored_hash = '$O$Bm3S4byeCnk3hLAL2ga3k4CtZM5frA0';
    // our password to run against the stored hash
    $password = 'asdf';
    $hash->check($password, $stored_hash);

And, generating a password hash for storage...
    // include OfHash file beforehand however you want
    $hash = new OfHash();
    // get our password for storage here
    // $password = 'asdf';
    $stored_hash = $hash->hash($password);
    // store the var $stored_hash however you want

As a note, OfHash only needs instantiated once.  You can reuse it multiple times for hashing passwords and checking hashes against password input without a problem.

I can fork and send a pull request later, but right now I'm in the middle of setting up a VPS, and setting up its firewall.  If I don't have it done by the end of the week, just give me a poke message here on github as a reminder.

**Comment by katanacrimson** [comment]
https://github.com/Obsidian1510/MineAdmin/tree/ofhash

Take a look at the commits for how I've made my swing at working it in -- it's more of an implementation example more than anything, don't be afraid to do it however you want.

Also, for fun, try running generate_ofhash.php with the same value in $password - every time it generates, you've got a different hash...and yet it still works when validating that password.  ;)

**Comment by resba** [comment]
I wish I had seen the implementation example before hand. I'll work on implementing this.

**Comment by katanacrimson** [comment]
It's /kinda/ available still, IIRC.  Link moved though when I renamed my account.

https://github.com/damianb/MineAdmin/tree/ofhash

**Comment by katanacrimson** [comment]
Oh, and also, we've modified OfHash in the OpenFlame framework repository for full-size hashes.  Hash size increases to about 90 or so characters (edit: 98 characters to be exact), I can't remember exactly how long they are.

The latest copy of OfHash in the repo:
https://github.com/OpenFlame/OpenFlame-Framework/blob/master/src/OfHash.php

**Comment by resba** [comment]
Alright, I'll use this. Also, thanks for the example! It will really help! Quick question though, should I use it as a class.php file or as a .php file? (when implementing) Kinda new to PHP Classes.

**Comment by katanacrimson** [comment]
Either or, but within OpenFlame we don't use the .class.php bit, just .php -- we use an autoloader which just loads by the class name.

It's up to you in the end, but I find the ".class" chunk unnecessary in everything I've written, especially when it's making heavy use of object-oriented programming (example: https://github.com/damianb/yukari )

**Comment by katanacrimson** [comment]
As a heads up, there may be an update to OfHash in the very near future, to help harden it against a newer more accurate breed of timing attacks.  Right now I'm working with someone else to get a solution licensed public domain or a compatible license so that OfHash will have the hardening in place.

**Comment by resba** [comment]
I've spent awhile on this. I'm going to backburner it because i have botch the code so badly i think im just going to archive this and wait for your update.

**Comment by katanacrimson** [comment]
FWIW, there won't be any external API changes for OfHash, as the update will be totally localized within the class itself.  You can continue developing at will, just be ready to overwrite the old OfHash file contents with the new stuff when it is ready.

... Slightly off topic -
I never thought I'd be saying or doing this, but the hardening change is actually an intentional _de_optimization of the internal code.
o.O

**Comment by resba** [comment]
I will, but the problem i'm facing right now (and i'm glad im backing away right now so I can take a breather) is that the hash generator generates different hashes for the same word. I don't know what I should do in order to make it use one consistent hash per word, or im probably missing the point entirely.

**Comment by katanacrimson** [comment]
See my commit comment on https://github.com/resba/MineAdmin/commit/bb178d2c0cba4c000fe4218cb2c8d9d02adf0512; the fluid hash generation is entirely intentional for enhancing hash security.  More details about it right there.

**Comment by katanacrimson** [comment]
https://github.com/OpenFlame/OpenFlame-Framework/commit/5ef965bd1bfbee942bf6de2aca665c0e9eb33b6f

Changes are live now that @padraicb on twitter has released the function used into the public domain.

Latest copy: https://github.com/OpenFlame/OpenFlame-Framework/blob/master/src/OfHash.php

**Comment by chemicalfire** [comment]
is it necessary?
